### ISSUE TITLE
编译完成r8125-esxi-9.009.00，征集测试

### ISSUE THREAD

**Issue by lengfwong** [realganfan/r8125-esxi#12]
https://github.com/lengfwang/r8125-esxi6.7/blob/r8125-esxi/net-r8125-9.009.00-4.vib
按照原作者ganfan的教程，编译了一把 9.009.00 版，现征集测试：

说明：
1.该驱动编译后，本人测试有限。可能不稳定，甚至可能导致不可预知的灾难性后果，请做好故障预案，请勿用于生产。
2.本人已尽提醒义务。您必须了解使用本软件的风险，您将出于自愿测试使用本驱动，本人不承诺提供任何形式的技术支持、使用担保，也不承担任何因使用本驱动而产生问题的相关责任。您若下载，则代表同意。（copy from @shuxin，thanks：）
3.基本函数，网卡驱动类的更是两眼发黑，不明白参数含义，完全抄袭realganfan的，若有高手可参考修改的9.009.01 https://github.com/lengfwang/r8125-esxi6.7
4.基本功能正常，用做WAN口的pppoe拨号端口吊死问题正在测试，还未知。VLAN测试正常。
ps：编译的9.009.00-1第一版，引起esxi无法启动，此为第二版，现使用正常。

**Comment by lengfwong** [comment]
问题：我的WAN口做PPPOE还是吊死，不知道原因。：-（

**Comment by jiajiaxd** [comment]
经测试，基本的上网功能没问题，感谢。

**Comment by jiajiaxd** [comment]
经测试，存在用一会儿网就断的问题，重新插拔网线可以恢复网络

**Comment by FarrowE** [comment]
esxcli software vib install -v file:///vmfs/volumes/datastore1/net-r8125.vib --dry-run
 [VibDownloadError]
 ('/vmfs/volumes/datastore1/net-r8125.vib', 'Bad VIB archive header')
        url = file:///vmfs/volumes/datastore1/net-r8125.vib
 Please refer to the log file for more details.
为啥不能安装？

**Comment by lengfwang** [comment]
> 经测试，存在用一会儿网就断的问题，重新插拔网线可以恢复网络



> 经测试，存在用一会儿网就断的问题，重新插拔网线可以恢复网络

我的lan口不断，用作WAN口pppoe拨号一段时间后就会断开，原因未知。用iperf3满速测试，会有百分之零点几的丢包。

**Comment by lengfwong** [comment]
> 经测试，存在用一会儿网就断的问题，重新插拔网线可以恢复网络

我的lan口不断，用做WAN口pppoe拨号时，多一段时间就会断，似乎时端口拥塞。iperf3满速测试会有百分之零点几的丢包。

**Comment by lengfwong** [comment]
鸽了，原来看过一个视频说ESXI对硬件性能损失最小，所以一直想用这个，奈何网络不给力，转战PVE了。装了7.0，核显直通良好。

**Comment by icekingcy** [comment]
@lengfwang  驱动更新了，可以编译更新下吗？

<html>
<body>


2.5G Ethernet LINUX driver r8125 for kernel up to 5.19 | 9.009.02 | 2022/07/08 | 88 KB
-- | -- | -- | --



</body>
</html>

**Comment by Dengchaojun** [comment]
请问可否编译一个RTL8125驱动用于ESXi 7.0. 请教哪里有教程？

**Comment by lengfwong** [comment]
> @lengfwang 驱动更新了，可以编译更新下吗？
> 
> 2.5G Ethernet LINUX driver r8125 for kernel up to 5.19	9.009.02	2022/07/08	88 KB

比较了下9.009.02没有多大改善，主要是适配了5.19，对ESXI6.7没用。

**Comment by lengfwong** [comment]
> 请问可否编译一个RTL8125驱动用于ESXi 7.0. 请教哪里有教程？

我在网上找了好久，除了realganfan这个项目没见有别的大神写教程，据说ESXI 7.0架构变了，适配难度更大，没办法，我改用PVE了

**Comment by wentijianihao** [comment]
> https://github.com/lengfwang/r8125-esxi6.7/blob/r8125-esxi/net-r8125-9.009.00-4.vib 按照原作者ganfan的教程，编译了一把 9.009.00 版，现征集测试：
> 
> 说明： 1.该驱动编译后，本人测试有限。可能不稳定，甚至可能导致不可预知的灾难性后果，请做好故障预案，请勿用于生产。 2.本人已尽提醒义务。您必须了解使用本软件的风险，您将出于自愿测试使用本驱动，本人不承诺提供任何形式的技术支持、使用担保，也不承担任何因使用本驱动而产生问题的相关责任。您若下载，则代表同意。（copy from @shuxin，thanks：） 3.基本函数，网卡驱动类的更是两眼发黑，不明白参数含义，完全抄袭realganfan的，若有高手可参考修改的9.009.01 https://github.com/lengfwang/r8125-esxi6.7 4.基本功能正常，用做WAN口的pppoe拨号端口吊死问题正在测试，还未知。VLAN测试正常。 ps：编译的9.009.00-1第一版，引起esxi无法启动，此为第二版，现使用正常。

您好，您提及“引起esxi无法启动”，想知道怎么能够恢复如安装前呢？拜托
